docs(index): add swot analysis
2023M5T1-Inteli/grupo3 pull request #16
Opened 2023-02-02 20:21 UTC by gabriosilva

2023-02-03 18:17 UTC, gabriosilva commented on docs/index.md
> +- Investir na formação dos funcionários
```suggestion
### Oportunidades
- Alianças e cooperação com outras empresas do mesmo setor e países aliados ao brasil
- Participação em programas governamentais
- Expansão internacional
- Investir na formação dos funcionários
- Alta Barreira para novos entrantes
```

2023-02-03 18:20 UTC, gabriosilva commented on docs/index.md
> +- Cliente consolidao
```suggestion
- Cliente consolidado
```

2023-02-03 18:21 UTC, gabriosilva commented on docs/index.md
> +- Mudanças no escopo poílitico nacional
```suggestion
- Mudanças no escopo político nacional
```

2023-02-03 18:28 UTC, IaagoTavares requested changes

2023-02-03 18:28 UTC, IaagoTavares commented on docs/index.md
> +- Cliente consolidao
```suggestion
- Maior cliente (Governo) possui uma estabilidade financeira, garantindo maior previsibilidade dos recursos 
```

2023-02-06 18:36 UTC, gabriosilva commented on docs/index.md
> +- Uso de indústrias locais para o fornecimento de matéria-prima
```suggestion
- Cadeia de fornecimento global para matéria-prima
```

2023-02-08 20:10 UTC, gabriosilva commented
> Será que tem que usar o template daqui: https://drive.google.com/drive/folders/1lTqisJ_gxxtc5J5aXM8ula2kQ4MsII_M?

sim!! vou trocar aqui

2023-02-09 01:59 UTC, gbcarneiro approved these changes

2023-02-09 09:24 UTC, dtonavitor approved these changes

2023-02-09 16:38 UTC, Lederback approved these changes

2023-02-09 17:03 UTC, merged