docs: inclusão do problema
2023M5T1-Inteli/grupo3 pull request #19
Opened 2023-02-07 19:59 UTC by IaagoTavares

2023-02-07 20:04 UTC, Lederback approved these changes

2023-02-07 20:04 UTC, gbcarneiro reviewed
tá perfeito

2023-02-07 20:05 UTC, gbcarneiro approved these changes

2023-02-07 20:06 UTC, gbcarneiro approved these changes

2023-02-07 20:21 UTC, gbcarneiro approved these changes

2023-02-08 19:49 UTC, gabriosilva requested changes
some changes

2023-02-08 19:49 UTC, gabriosilva commented on docs/index.md
> +Na visualização do banco de dados do terreno, será utilizado o software GIS, que é um sistema que conecta dados a um mapa, integrando dados de localização, onde as coisas estão, com todos os tipos de
"como as coisas", na última frase, acho que pode soar um pouco redundante

2023-02-08 20:19 UTC, merged