docs: add introdução do artigo
2023M5T1-Inteli/grupo3 pull request #40
Opened 2023-02-15 20:39 UTC by dtonavitor

## O que esse PR faz:
Adiciona a introdução do artigo científico.

## Observações:
Validar os seguintes pontos:

- Introduz o assunto/problema.
- Apresenta o motivo deste assunto/problema ser relevante.
- Explica como este trabalho está relacionado e pode contribuir para tratar deste assunto/problema.

2023-02-22 17:23 UTC, gabriosilva requested changes
Just a simple change, overall, seems great!

2023-02-22 18:05 UTC, IaagoTavares approved these changes

2023-02-23 17:14 UTC, Lederback approved these changes

2023-02-24 16:00 UTC, fredschur approved these changes

2023-02-24 17:07 UTC, gabriosilva approved these changes
lgtm!

2023-02-24 18:49 UTC, merged