feature: rota implementada
2023M5T1-Inteli/grupo3 pull request #67
Opened 2023-03-09 00:59 UTC by gbcarneiro

## O que esse PR faz:
- Implementa o SpringBoot em nossa aplicação principal

## Observações:

2023-03-12 15:45 UTC, gabriosilva commented on src/main/resources/application.properties
> -
You should maintain these lines, but just anonymize the values.

Something like spring.data.mongodb.uri=DATABASE-URI.

It indicates what kind of value it expects, but doesn't show them.

2023-03-12 15:58 UTC, gabriosilva requested changes
Just a simple change.

Another thing, shouldn't we use the MVC structure for the routes?
We are currently defining all routes on the Main.java, but it may be a problem.
(Implementation example: https://spring.io/guides/gs/rest-service/)

2023-03-12 23:12 UTC, Lederback approved these changes

2023-03-12 23:58 UTC, gabriosilva approved these changes
LGTM!

2023-03-13 00:09 UTC, felipesampaiosilva approved these changes

2023-03-13 00:53 UTC, merged